services:
 mongo:
  image: mongo:latest
  ports:
    - 27017:27017
  volumes:
    - mongodb_data_container:/data/db
 review-service-ex:
  depends_on:
    - mongo
  image: miverboven/review-service-ex
  ports:
    - 8052:8052
  links:
    - mongo
  environment:
   MONGODB_PORT: 27017
   MONGODB_HOST: mongo
volumes:
 mongodb_data_container:
